### ISSUE TITLE
Checklist for merging of decouple work

### ISSUE THREAD

**Issue by galak** [OpenAMP/open-amp#90]
- RPMSG:
   - [x] Close on changes for static endpoint support, rename new endpoint callback to endpoint announcement callback. (PR #98)
   - [x] Review changes to remove shmem (PR #99)
   - [x] Style review -- checkpatch.pl?
   - [x] Make MASTER/SLAVE a cmake option (PR #100)
   - [x] Code review
- Remoteproc:
   - [ ] Code review
- General:
   - [X] Update apps for new api changes. (PR #103)
   - [ X] Rework dir struct of apps into examples/ & tests (tests is echo + api) (PR #101)
- Testing:
   - [X] Decouple apps platform code from remoteproc (PR #104)
   - [x] Message Tests:
          [ ] RPC demo
   - [ ] Message test development:
        - [ X ] Linux Kernel driver for msg test (master)
        - [ ] Zephyr master/slave for msg test
        - [ X ] Bare Metal master/slave for msg test
        - [ X ] Linux OpenAMP Userspace master/slave for msg test
   - [ ] Message test validation:
        - [x] Master: Linux OpenAMP Userspace / Slave: Linux Openamp Userspace [posix] (x86 linux)
        - [x] Master: Linux OpenAMP Userspace / Slave: Bare Metal (uio) (Zync UltraScale+)
        - [x] Master: Linux Kernel / Slave: Bare Metal (Zync UltraScale+, ST Platform)
        - [x] Master: Linux Kernel / Slave: Zephyr (ST Platform)
        - [x] Master: Bare Metal / Slave: Bare Metal (Zync UltraScale+)
        - [ ] Master: Bare Metal / Slave: Linux Openamp Userspace (uio) (Zync UltraScale+)
        - [ ] Master: Zephyr / Slave: Zephyr (NXP)
   - [ ] RPMsg functional testing suite (PR #106)
   - [x] Test OpenAMP apps on Zync platform
   - [ ] Zephyr - implement slave support
   - [x] Add 'slave' app to match Linux Kernel samples/rpmsg/rpmsg_client_sample.c (PR #102)
   - [ ] Test 'slave' app on ST platform w/Zephyr
   - [x] Update proxy support (PR #107)
